# Generated by Django 5.2.4 on 2025-08-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_blocked"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_block_user", "Может блокировать пользователей"),
                    ("can_view_user", "Может просматривать все объекты"),
                    ("can_finish_mailing", "Может отключить рассылку"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
