# Generated by Django 5.2.4 on 2025-08-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_block_user", "Может блокировать пользователей"),
                    ("can_view_user", "Может просматривать список пользователей"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
