# Generated by Django 5.2.4 on 2025-08-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailingserv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=255, verbose_name="Тема письма"),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Введите текст сообщения", verbose_name="Тело письма"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
