# Generated by Django 5.2.4 on 2025-08-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailingserv", "0004_attempt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailing",
            old_name="recipients",
            new_name="clients",
        ),
    ]
