# Generated by Django 5.2.4 on 2025-08-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailingserv", "0006_client_owner_mailing_owner_message_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_subscribed",
            field=models.BooleanField(
                default=True, verbose_name="Подписан на рассылку"
            ),
        ),
    ]
