# Generated by Django 5.2.4 on 2025-08-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailingserv", "0007_mailing_is_subscribed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="is_subscribed",
        ),
    ]
