# Generated by Django 5.2.4 on 2025-08-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailingserv", "0008_remove_mailing_is_subscribed"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_subscribed",
            field=models.BooleanField(
                default=True, verbose_name="Подписан на рассылку"
            ),
        ),
    ]
