# Generated by Django 5.2.4 on 2025-08-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailingserv", "0009_client_is_subscribed"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_subscribed",
            field=models.BooleanField(default=True, verbose_name="Включена"),
        ),
    ]
