# Generated by Django 5.2.4 on 2025-08-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailingserv", "0010_mailing_is_subscribed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [("can_view_client", "Может видеть список клиентов")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_all_mailing", "Может видеть все рассылки"),
                    ("can_finish_mailing", "Может отключить рассылку"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_view_message", "Может видеть список сообщений")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
